# Generated by Django 4.2.2 on 2025-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
