# Generated by Django 4.2.2 on 2023-07-11 12:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KalipMs',
            fields=[
                ('KalipNo', models.CharField(primary_key=True, serialize=False)),
                ('ProfilNo', models.CharField(null=True)),
                ('Kimlik', models.IntegerField(null=True)),
                ('FirmaKodu', models.CharField(null=True)),
                ('FirmaAdi', models.CharField(null=True)),
                ('Cinsi', models.CharField(null=True)),
                ('Miktar', models.FloatField(null=True)),
                ('Capi', models.FloatField(null=True)),
                ('UretimTarihi', models.DateTimeField(null=True)),
                ('GozAdedi', models.IntegerField(null=True)),
                ('Termin', models.DateTimeField(null=True)),
                ('Silindi', models.IntegerField(null=True)),
                ('Bolster', models.CharField(null=True)),
                ('KalipCevresi', models.FloatField(null=True)),
                ('KaliteOkey', models.IntegerField(null=True)),
                ('UreticiFirma', models.CharField(null=True)),
                ('TeniferOmruMt', models.FloatField(null=True)),
                ('TeniferOmruKg', models.FloatField(null=True)),
                ('SonTeniferTarih', models.DateTimeField(null=True)),
                ('SonTeniferKg', models.FloatField(null=True)),
                ('SonTeniferSebebi', models.CharField(null=True)),
                ('SonUretimTarih', models.DateTimeField(null=True)),
                ('SonUretimGr', models.FloatField(null=True)),
                ('UretimTenSonrasiKg', models.FloatField(null=True)),
                ('UretimToplamKg', models.FloatField(null=True)),
                ('ResimGramaj', models.FloatField(null=True)),
                ('KalipAciklama', models.CharField(null=True)),
                ('SikayetVar', models.IntegerField(null=True)),
                ('KaliteAciklama', models.CharField(null=True)),
                ('AktifPasif', models.CharField(null=True)),
                ('PresKodu', models.CharField(null=True)),
                ('ResimDizini', models.CharField(null=True)),
            ],
            options={
                'db_table': 'View020_KalipListe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kalip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilNo', models.CharField(null=True, verbose_name='Profil No')),
                ('kalipNo', models.CharField(null=True, verbose_name='Kalıp No')),
                ('cins', models.CharField(null=True, verbose_name='Cins')),
                ('profilGr', models.CharField(null=True, verbose_name='Profil gr')),
                ('cap', models.CharField(null=True, verbose_name='Çap')),
                ('goz', models.CharField(null=True, verbose_name='Figür Sayısı')),
                ('disCevresi', models.CharField(null=True, verbose_name='Dış Çevresi')),
                ('pres', models.CharField(null=True, verbose_name='Pres')),
                ('firma', models.CharField(null=True, verbose_name='Firma')),
                ('uretimTarihi', models.CharField(null=True, verbose_name='Üretim Tarihi')),
                ('yapanFirma', models.CharField(null=True, verbose_name='Yapan Firma')),
                ('tenSonrasiKg', models.CharField(null=True, verbose_name='Ten. Sonrası Kg')),
                ('topUretimKg', models.CharField(null=True, verbose_name='Top Üretim Kg')),
            ],
            options={
                'verbose_name': 'Kalıp',
                'verbose_name_plural': 'Kalıplar',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=255, verbose_name='Lokasyon İsmi')),
                ('isPhysical', models.BooleanField(verbose_name='Fiziksel Bir Konum mu?')),
                ('locationKalips', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='Lokasyondaki Kalıplar')),
                ('locationRelationID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArslanTakipApp.location')),
            ],
            options={
                'permissions': [('dg_view_location', 'OLP can view location')],
            },
        ),
        migrations.CreateModel(
            name='Hareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalipNo', models.CharField(verbose_name='Kalıp Numarası')),
                ('hareketTarihi', models.DateTimeField(auto_now=True, null=True)),
                ('kalipKonum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kalip_konum', to='ArslanTakipApp.location', verbose_name='Kalıp Konum')),
                ('kalipVaris', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kalip_varis', to='ArslanTakipApp.location', verbose_name='Kalıp Varış')),
                ('kimTarafindan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim Tarafından')),
            ],
            options={
                'verbose_name': 'Hareket',
                'verbose_name_plural': 'Hareketler',
            },
        ),
    ]
