# Generated by Django 4.2.2 on 2023-07-11 13:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationKalips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None, verbose_name='Lokasyondaki Kalıplar'),
        ),
    ]
