# Generated by Django 4.2.2 on 2023-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0002_alter_location_locationkalips'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiesLocation',
            fields=[
                ('kalipNo', models.CharField(primary_key=True, serialize=False, verbose_name='Kalıp Numarası')),
            ],
            options={
                'db_table': 'View1_KalipLastLocation',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='locationKalips',
        ),
    ]
