# Generated by Django 4.2.2 on 2023-07-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0003_dieslocation_remove_location_locationkalips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hareket',
            name='kalipKonum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kalip_konum', to='ArslanTakipApp.location', verbose_name='Kalıp Konum'),
        ),
    ]
