# Generated by Django 4.2.2 on 2023-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0005_remove_kalip_cap_remove_kalip_cins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalip',
            name='Hatali',
            field=models.IntegerField(null=True),
        ),
    ]
