# Generated by Django 4.2.2 on 2023-07-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0006_alter_kalip_hatali'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalip',
            name='kalipLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArslanTakipApp.location'),
        ),
    ]
