# Generated by Django 4.2.2 on 2023-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0007_kalip_kaliplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalip',
            name='PaketBoyu',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='kalip',
            name='SilinmeSebebi',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='kalip',
            name='TeniferKalanOmurKg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kalip',
            name='TeniferNo',
            field=models.IntegerField(null=True),
        ),
    ]
