# Generated by Django 4.2.2 on 2023-07-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0009_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('dg_view_location', 'Gorme Yetkisi Var'), ('gonder_view_location', 'Gonderme Yetkisi Var')]},
        ),
    ]
