# Generated by Django 4.2.2 on 2023-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0010_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresUretimRaporu',
            fields=[
                ('KalipNo', models.CharField(primary_key=True, serialize=False)),
                ('KartNo', models.IntegerField(null=True)),
                ('Tarih', models.DateTimeField(null=True)),
                ('Operator', models.CharField(null=True)),
                ('StokKodu', models.CharField(null=True)),
                ('StokCinsi', models.CharField(null=True)),
                ('PartiNo', models.CharField(null=True)),
                ('PresKodu', models.CharField(null=True)),
                ('PresAdi', models.CharField(null=True)),
                ('Gerceklesen', models.FloatField(null=True)),
                ('BaslamaSaati', models.DateTimeField(null=True)),
                ('BitisSaati', models.DateTimeField(null=True)),
                ('HataAciklama', models.CharField(null=True)),
                ('Durum', models.CharField(null=True)),
            ],
            options={
                'db_table': 'View062_PresUretimRaporu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiparisList',
            fields=[
                ('KartNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ProfilNo', models.CharField(null=True)),
                ('BulunduguYer', models.CharField(null=True)),
                ('Adet', models.FloatField(null=True)),
                ('KartAktif', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'View051_ProsesDepoListesi',
                'managed': False,
            },
        ),
    ]
