# Generated by Django 4.2.2 on 2023-08-30 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArslanTakipApp', '0011_presuretimraporu_siparislist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkSiparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EkNo', models.IntegerField(null=True)),
                ('EkPresKodu', models.CharField(null=True)),
                ('EkTermin', models.DateTimeField(null=True)),
                ('EkKg', models.FloatField(null=True, verbose_name='Ek Kg')),
                ('EkKalankG', models.FloatField(null=True, verbose_name='Ek Kalan Kg')),
                ('Ekleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EkSiparis',
                'verbose_name_plural': 'EkSiparisler',
            },
        ),
    ]
