# Generated by Django 4.2.2 on 2023-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0012_eksiparis'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksiparis',
            name='SipKartNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eksiparis',
            name='SipKimlik',
            field=models.IntegerField(null=True),
        ),
    ]
