# Generated by Django 4.2.2 on 2023-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0013_eksiparis_sipkartno_eksiparis_sipkimlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksiparis',
            name='Silindi',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='eksiparis',
            name='Sira',
            field=models.IntegerField(null=True),
        ),
    ]
