# Generated by Django 4.2.2 on 2023-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0014_eksiparis_silindi_eksiparis_sira'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksiparis',
            name='EkDurumu',
            field=models.CharField(null=True),
        ),
    ]
