# Generated by Django 4.2.2 on 2023-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0016_eksiparis_eksiparistamam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eksiparis',
            name='EkDurumu',
            field=models.FloatField(null=True),
        ),
    ]
