# Generated by Django 4.2.2 on 2023-08-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0018_eksiparis_ekadet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eksiparis',
            name='EkSiparisTamam',
        ),
    ]
