# Generated by Django 4.2.2 on 2023-08-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0019_remove_eksiparis_eksiparistamam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eksiparis',
            old_name='Ekleyen',
            new_name='KimTarafindan',
        ),
    ]
