# Generated by Django 4.2.2 on 2023-09-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0023_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('dg_view_location', 'Gorme Yetkisi Var'), ('gonder_view_location', 'Gonderme Yetkisi Var'), ('meydan_view_location', 'Meydan Gorme Yetkisi Var'), ('goz_view_location', 'Goz Gorme Yetkisi Var'), ('kalipEkran_view_location', 'Kalip Ekrani Gorme Yetkisi Var')]},
        ),
    ]
