# Generated by Django 4.2.2 on 2023-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0025_location_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePresFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MakineKodu', models.CharField(null=True)),
                ('Start', models.DateTimeField()),
                ('Stop', models.DateTimeField()),
                ('Parameters', models.JSONField(null=True)),
                ('Events', models.CharField(null=True)),
            ],
        ),
    ]
