# Generated by Django 4.2.2 on 2023-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0027_termik_alter_livepresfeed_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termik',
            name='BatchNo',
            field=models.CharField(null=True),
        ),
    ]
