# Generated by Django 4.2.2 on 2023-10-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0028_termik_batchno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
