# Generated by Django 4.2.2 on 2023-10-30 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArslanTakipApp', '0029_alter_location_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='YudaOnay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aciklama', models.CharField(blank=True, null=True)),
                ('Tarih', models.DateField(blank=True, null=True)),
                ('Onay', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YudaNo', models.CharField(blank=True, null=True)),
                ('Tarih', models.DateField(blank=True, null=True)),
                ('RevTarih', models.DateField(blank=True, null=True)),
                ('IstekYapanBolum', models.CharField(blank=True, null=True)),
                ('IstekYapanKisi', models.CharField(blank=True, null=True)),
                ('MusteriFirmaAdi', models.CharField(blank=True, null=True)),
                ('SonKullaniciFirma', models.CharField(blank=True, null=True)),
                ('OnemliYuzeyler', models.BooleanField(blank=True, null=True)),
                ('OnemliOlculerVeToleranslar', models.CharField(blank=True, null=True)),
                ('CizimNo', models.CharField(blank=True, null=True)),
                ('YillikProfilSiparisi', models.CharField(blank=True, null=True)),
                ('TalasliImalat', models.CharField(blank=True, null=True)),
                ('TalasliImalatBoyaYadaEloksaldan', models.CharField(blank=True, null=True)),
                ('MusteriYuzeyVeyaTalasliIslem', models.CharField(blank=True, null=True)),
                ('BirlikteCalisanAparati', models.CharField(blank=True, null=True)),
                ('OzelPaketleme', models.BooleanField(blank=True, null=True)),
                ('OzelPaketlemeAciklama', models.CharField(blank=True, null=True)),
                ('KalipDurumu', models.CharField(blank=True, null=True)),
                ('BilletCinsi', models.CharField(blank=True, null=True)),
                ('Kondusyon', models.CharField(blank=True, null=True)),
                ('DinToleransi', models.CharField(blank=True, null=True)),
                ('YuzeyDurumu', models.CharField(blank=True, null=True)),
                ('MetreAgirlikTalebi', models.BooleanField(blank=True, null=True)),
                ('MetreAgirlikTalebiMiktar', models.CharField(blank=True, null=True)),
                ('AskiIzi', models.CharField(blank=True, null=True)),
                ('IstenilenStandartBoy', models.CharField(blank=True, null=True)),
                ('MinKullanimBoyu', models.CharField(blank=True, null=True)),
                ('Folyo', models.BooleanField(blank=True, null=True)),
                ('Bariyerleme', models.BooleanField(blank=True, null=True)),
                ('MusteriOdemeVadesi', models.CharField(blank=True, null=True)),
                ('KaliphaneBolumuOnay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onay_kaliphane', to='ArslanTakipApp.yudaonay')),
                ('KaliteBolumuOnay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onay_kalite', to='ArslanTakipApp.yudaonay')),
                ('MekanikIslemBolumuOnay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onay_mekanik', to='ArslanTakipApp.yudaonay')),
                ('ProjeYoneticisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SatisBolumuOnay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onay_satis', to='ArslanTakipApp.yudaonay')),
                ('UretimBolumuOnay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onay_uretim', to='ArslanTakipApp.yudaonay')),
                ('YuzeyIslemBolumuOnay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onay_yuzey', to='ArslanTakipApp.yudaonay')),
            ],
        ),
    ]
