# Generated by Django 4.2.2 on 2023-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0032_rename_aciklama_comment_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuda',
            name='Tarih',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
