# Generated by Django 4.2.2 on 2023-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0033_alter_yuda_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Isim', models.CharField(blank=True, null=True)),
                ('Tag', models.CharField(blank=True, null=True)),
                ('ParentId', models.ManyToManyField(blank=True, null=True, to='ArslanTakipApp.parameter')),
            ],
        ),
    ]
