# Generated by Django 4.2.2 on 2023-11-24 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArslanTakipApp', '0034_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yuda',
            name='AskiIzi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='Bariyerleme',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='BilletCinsi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='BirlikteCalisanAparati',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='CizimNo',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='DinToleransi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='Folyo',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='IstekYapanBolum',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='IstekYapanKisi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='IstenilenStandartBoy',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='KalipDurumu',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='KaliphaneBolumuOnay',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='KaliteBolumuOnay',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='Kondusyon',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='MekanikIslemBolumuOnay',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='MetreAgirlikTalebi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='MetreAgirlikTalebiMiktar',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='MinKullanimBoyu',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='MusteriFirmaAdi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='MusteriOdemeVadesi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='MusteriYuzeyVeyaTalasliIslem',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='OnemliOlculerVeToleranslar',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='OnemliYuzeyler',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='OzelPaketleme',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='OzelPaketlemeAciklama',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='ProjeYoneticisi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='RevTarih',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='SatisBolumuOnay',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='SonKullaniciFirma',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='TalasliImalat',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='TalasliImalatBoyaYadaEloksaldan',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='Tarih',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='UretimBolumuOnay',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='YillikProfilSiparisi',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='YudaNo',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='YuklenenDosyalar',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='YuzeyDurumu',
        ),
        migrations.RemoveField(
            model_name='yuda',
            name='YuzeyIslemBolumuOnay',
        ),
        migrations.CreateModel(
            name='YudaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YudaNo', models.CharField(blank=True, null=True)),
                ('Tarih', models.DateField(auto_now=True, null=True)),
                ('RevTarih', models.DateField(blank=True, null=True)),
                ('MusteriFirmaAdi', models.CharField(blank=True, null=True)),
                ('SonKullaniciFirma', models.CharField(blank=True, null=True)),
                ('KullanımAlani', models.CharField(blank=True, null=True)),
                ('CizimNo', models.CharField(blank=True, null=True)),
                ('ProfilSiparisi', models.CharField(blank=True, null=True)),
                ('MusteriOdemeVadesi', models.CharField(blank=True, null=True)),
                ('AlasimKondusyon', models.JSONField(blank=True, null=True)),
                ('DinTolerans', models.CharField(blank=True, null=True)),
                ('MetreAgirlikTalebi', models.CharField(blank=True, null=True)),
                ('MATmin', models.CharField(blank=True, null=True)),
                ('MATmax', models.CharField(blank=True, null=True)),
                ('OnemliOlculer', models.CharField(blank=True, null=True)),
                ('YuzeyPres', models.JSONField(blank=True, null=True)),
                ('YuzeyEloksal', models.JSONField(blank=True, null=True)),
                ('YuzeyBoya', models.JSONField(blank=True, null=True)),
                ('YuzeyAhsap', models.JSONField(blank=True, null=True)),
                ('TalasliImalat', models.CharField(blank=True, null=True)),
                ('TalasliImalatAciklama', models.CharField(blank=True, null=True)),
                ('Paketleme', models.CharField(blank=True, null=True)),
                ('PaketlemeAciklama', models.CharField(blank=True, null=True)),
                ('ProjeYoneticisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='yuda_projeyoneticisi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, null=True)),
                ('file', models.FileField(upload_to='media/')),
                ('my_yuda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='ArslanTakipApp.yudaform')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='Form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArslanTakipApp.yudaform'),
        ),
    ]
