# Generated by Django 4.2.2 on 2023-11-24 10:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0035_remove_yuda_askiizi_remove_yuda_bariyerleme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yudaform',
            name='BirlikteCalisan',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=3),
        ),
    ]
