# Generated by Django 4.2.2 on 2023-11-25 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArslanTakipApp', '0036_yudaform_birliktecalisan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='my_yuda',
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='media/')),
                ('FileTitle', models.CharField(blank=True, null=True)),
                ('FileModel', models.CharField(blank=True, null=True)),
                ('FileModelId', models.CharField(blank=True, null=True)),
                ('UploadDate', models.DateField(auto_now=True, null=True)),
                ('Note', models.CharField(blank=True, null=True)),
                ('OriginFile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ArslanTakipApp.uploadfile')),
                ('UploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
