# Generated by Django 4.2.2 on 2023-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0037_remove_myfile_file_remove_myfile_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='EklenenDosyalar',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Form',
        ),
        migrations.AddField(
            model_name='comment',
            name='FormModel',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='FormModelId',
            field=models.CharField(blank=True, null=True),
        ),
    ]
