# Generated by Django 4.2.2 on 2023-12-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0038_remove_comment_eklenendosyalar_remove_comment_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yudaform',
            name='ProfilSip',
            field=models.CharField(blank=True, null=True),
        ),
    ]
