# Generated by Django 4.2.2 on 2023-12-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0039_yudaform_profilsip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yudaform',
            old_name='ProfilSiparisi',
            new_name='YillikProfilSiparisiMiktar',
        ),
    ]
