# Generated by Django 4.2.2 on 2023-12-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0040_rename_profilsiparisi_yudaform_yillikprofilsiparisimiktar'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='FileSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
