# Generated by Django 4.2.2 on 2023-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0041_uploadfile_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='yudaform',
            name='ProfilMiktarBirim',
            field=models.CharField(blank=True, null=True),
        ),
    ]
