# Generated by Django 4.2.2 on 2023-12-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0042_yudaform_profilmiktarbirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yudaform',
            name='RevTarih',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='yudaform',
            name='Tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
