# Generated by Django 4.2.2 on 2023-12-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0044_rename_onay_yudaonay_onaydurumu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yudaonay',
            options={'permissions': [('gorme_yuda', 'Yuda Gorme Yetkisi Var')]},
        ),
    ]
