# Generated by Django 4.2.2 on 2023-12-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0045_alter_yudaonay_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yudaform',
            options={'permissions': [('gorme_yuda', 'Yuda Gorme Yetkisi Var')]},
        ),
        migrations.AlterModelOptions(
            name='yudaonay',
            options={},
        ),
    ]
