# Generated by Django 4.2.2 on 2024-03-04 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArslanTakipApp', '0046_alter_yudaform_options_alter_yudaonay_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yudaform',
            options={'permissions': [('gorme_yuda', 'Yuda Gorme Yetkisi Var')], 'verbose_name': 'YudaForm', 'verbose_name_plural': 'YudaForms'},
        ),
        migrations.AddField(
            model_name='yudaform',
            name='YudaAcanKisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='yuda_acankisi', to=settings.AUTH_USER_MODEL),
        ),
    ]
