# Generated by Django 4.2.2 on 2024-03-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ArslanTakipApp', '0047_alter_yudaform_options_yudaform_yudaacankisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yudaonay',
            name='Kullanici',
        ),
        migrations.AddField(
            model_name='yudaonay',
            name='Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
