# Generated by Django 4.2.2 on 2024-03-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0050_alter_yudaform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ReplyTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ArslanTakipApp.comment'),
        ),
    ]
