# Generated by Django 4.2.2 on 2024-03-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0051_comment_replyto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yudaform',
            options={'permissions': [('gorme_yuda', 'Yuda Gorme Yetkisi Var'), ('yonetici_yuda', 'Yuda Proje Yoneticisi'), ('acan_yuda', 'Yuda Acan Kisi')], 'verbose_name': 'YudaForm', 'verbose_name_plural': 'YudaForms'},
        ),
    ]
