# Generated by Django 4.2.2 on 2024-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0052_alter_yudaform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='yudaform',
            name='GüncelTarih',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
