# Generated by Django 4.2.2 on 2024-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0053_yudaform_günceltarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yudaform',
            name='RevTarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
