# Generated by Django 4.2.2 on 2024-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0054_alter_yudaform_revtarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yudaform',
            name='GüncelTarih',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='yudaform',
            name='RevTarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yudaform',
            name='Tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
