# Generated by Django 4.2.2 on 2024-04-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0058_alter_notification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='where_id',
            field=models.IntegerField(null=True),
        ),
    ]
