# Generated by Django 4.2.2 on 2024-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0059_notification_where_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yudaform',
            name='GüncelTarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
