# Generated by Django 4.2.2 on 2024-04-17 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArslanTakipApp', '0060_alter_yudaform_günceltarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Slindi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yudaform',
            name='Silindi_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
