# Generated by Django 4.2.2 on 2024-04-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0061_comment_slindi_yudaform_silindi_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Slindi',
            new_name='Silindi',
        ),
    ]
