# Generated by Django 4.2.2 on 2024-04-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0062_rename_slindi_comment_silindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
