# Generated by Django 4.2.2 on 2024-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0064_notification_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Silindi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_marked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='where_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
