# Generated by Django 4.2.2 on 2024-04-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0066_notification_new_made_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='made_by',
            new_name='col_marked',
        ),
    ]
