# Generated by Django 4.2.2 on 2024-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0068_comment_viewedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='EditTarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
