# Generated by Django 4.2.2 on 2024-05-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0069_comment_edittarih_alter_comment_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yudaonay',
            name='Yuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='yudaonay', to='ArslanTakipApp.yudaform'),
        ),
    ]
