# Generated by Django 4.2.2 on 2024-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0071_eksiparis_ekbilletturu'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksiparis',
            name='EkYuzeyOzelligi',
            field=models.CharField(null=True),
        ),
    ]
