# Generated by Django 4.2.2 on 2024-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0072_eksiparis_ekyuzeyozelligi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksiparis',
            name='KalipSokmeSebebi',
            field=models.CharField(blank=True, null=True),
        ),
    ]
