# Generated by Django 4.2.2 on 2024-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0073_eksiparis_kalipsokmesebebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksiparis',
            name='ProfilNo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
