# Generated by Django 4.2.2 on 2024-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0074_eksiparis_profilno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eksiparis',
            old_name='KalipSokmeSebebi',
            new_name='UretimBitirmeSebebi',
        ),
        migrations.AddField(
            model_name='eksiparis',
            name='HataKodu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eksiparis',
            name='UretimBitirmeSebebiAciklama',
            field=models.CharField(blank=True, null=True),
        ),
    ]
