# Generated by Django 4.2.2 on 2024-05-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0075_rename_kalipsokmesebebi_eksiparis_uretimbitirmesebebi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eksiparis',
            name='HataKodu',
        ),
        migrations.RemoveField(
            model_name='eksiparis',
            name='UretimBitirmeSebebi',
        ),
        migrations.RemoveField(
            model_name='eksiparis',
            name='UretimBitirmeSebebiAciklama',
        ),
        migrations.CreateModel(
            name='SiparisKalip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KalipNo', models.CharField(blank=True, null=True)),
                ('Durum', models.CharField(blank=True, null=True)),
                ('HataKodu', models.CharField(blank=True, null=True)),
                ('UretimBitirmeSebebi', models.CharField(blank=True, null=True)),
                ('UretimBitirmeSebebiAciklama', models.CharField(blank=True, null=True)),
                ('EkSiparisBilgi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ArslanTakipApp.eksiparis')),
            ],
        ),
    ]
