# Generated by Django 4.2.2 on 2024-05-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0076_remove_eksiparis_hatakodu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiparisKalip',
            new_name='EkSiparisKalip',
        ),
    ]
