# Generated by Django 4.2.2 on 2024-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0077_rename_sipariskalip_eksipariskalip'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksipariskalip',
            name='Tarih',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='eksipariskalip',
            name='Uretim',
            field=models.CharField(blank=True, null=True),
        ),
    ]
