# Generated by Django 4.2.2 on 2024-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0079_yudaform_yenikalipno'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProcessEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
