# Generated by Django 4.2.2 on 2024-07-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0080_lastprocessemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('conversion_factor', models.IntegerField(blank=True, null=True)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('base_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArslanTakipApp.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
            },
        ),
    ]
