# Generated by Django 4.2.2 on 2024-07-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0082_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
