# Generated by Django 4.2.2 on 2024-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0083_personel_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCheckedUretimRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor_kimlik', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
