# Generated by Django 4.2.2 on 2024-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0084_lastcheckeduretimraporu'),
    ]

    operations = [
        migrations.CreateModel(
            name='UretimBasilanBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Siralama', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UretimBasilanBillet',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='lastcheckeduretimraporu',
            name='rapor_kimlik',
        ),
        migrations.AddField(
            model_name='lastcheckeduretimraporu',
            name='PresTestereNo',
            field=models.IntegerField(null=True),
        ),
    ]
