# Generated by Django 4.2.2 on 2024-07-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0085_uretimbasilanbillet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastcheckeduretimraporu',
            old_name='PresTestereNo',
            new_name='Siralama',
        ),
    ]
