# Generated by Django 4.2.2 on 2024-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0086_rename_prestestereno_lastcheckeduretimraporu_siralama'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='presKodu',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
