# Generated by Django 4.2.2 on 2024-07-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0087_location_preskodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='yudaform',
            name='OnayDurumu',
            field=models.CharField(blank=True, null=True),
        ),
    ]
