# Generated by Django 4.2.2 on 2024-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0088_yudaform_onaydurumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcheckeduretimraporu',
            name='TarihSaat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
