# Generated by Django 4.2.2 on 2024-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0089_lastcheckeduretimraporu_tarihsaat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hareket',
            name='aciklama',
            field=models.CharField(blank=True, null=True),
        ),
    ]
