# Generated by Django 4.2.2 on 2024-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0090_hareket_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='YudaOnayDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuda_id', models.IntegerField(blank=True, null=True)),
                ('kaliphane_onay_durumu', models.IntegerField(blank=True, null=True)),
                ('satis_onay_durumu', models.IntegerField(blank=True, null=True)),
                ('mekanik_islem_onay_durumu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'View1_YudaDurum4',
                'managed': False,
            },
        ),
    ]
