# Generated by Django 4.2.2 on 2024-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0091_yudaonaydurum'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksiparis',
            name='Aktif',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eksiparis',
            name='PresGrubu',
            field=models.CharField(blank=True, null=True),
        ),
    ]
