# Generated by Django 4.2.2 on 2024-09-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0097_presuretimtakip_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presuretimtakip',
            name='billet_boy_adet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
