# Generated by Django 4.2.2 on 2024-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0098_presuretimtakip_billet_boy_adet'),
    ]

    operations = [
        migrations.CreateModel(
            name='HammaddeBilletTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parti_no', models.CharField(blank=True, null=True)),
                ('boy', models.FloatField(blank=True, null=True)),
                ('adet', models.IntegerField(blank=True, null=True)),
                ('kg', models.FloatField(blank=True, null=True)),
                ('irsaliye_no', models.CharField(blank=True, null=True)),
                ('billet', models.CharField(blank=True, null=True)),
                ('stok_kodu', models.CharField(blank=True, null=True)),
                ('stok_cinsi', models.CharField(blank=True, null=True)),
                ('transfer_giren_kg', models.IntegerField(blank=True, null=True)),
                ('uretim_kg', models.FloatField(blank=True, null=True)),
                ('kalan_kg', models.FloatField(blank=True, null=True)),
                ('cap', models.IntegerField(blank=True, null=True)),
                ('aciklama', models.CharField(blank=True, null=True)),
                ('agirlik', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
