# Generated by Django 4.2.2 on 2024-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0099_hammaddebillettakip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HammaddePartiListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Billet', models.CharField(blank=True, null=True)),
                ('DepoKodu', models.CharField(blank=True, null=True)),
                ('StokKodu', models.CharField(blank=True, null=True)),
                ('StokCincsi', models.CharField(blank=True, null=True)),
                ('PartiNo', models.CharField(blank=True, null=True)),
                ('TransferCikanKg', models.FloatField(blank=True, null=True)),
                ('UretimKg', models.FloatField(blank=True, null=True)),
                ('KalanKg', models.FloatField(blank=True, null=True)),
                ('Cap', models.FloatField(blank=True, null=True)),
                ('Aciklama', models.CharField(blank=True, null=True)),
                ('Agirlik', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'View044_HammaddePartiListesi',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='hammaddebillettakip',
            name='cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hammaddebillettakip',
            name='transfer_giren_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
