# Generated by Django 4.2.2 on 2024-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0100_hammaddepartilistesi_alter_hammaddebillettakip_cap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilletDepoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(blank=True, null=True)),
                ('GirenPartiNo', models.CharField(blank=True, null=True)),
                ('GirenBoy', models.FloatField(blank=True, null=True)),
                ('GirenAdet', models.FloatField(blank=True, null=True)),
                ('GirenKg', models.FloatField(blank=True, null=True)),
                ('GirenDepoKodu', models.CharField(blank=True, null=True)),
                ('Aciklama', models.CharField(blank=True, null=True)),
                ('StokCinsi', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BilletDepoTransfer',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='hammaddebillettakip',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
