# Generated by Django 4.2.2 on 2024-10-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0101_billetdepotransfer_hammaddebillettakip_kayit_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammaddebillettakip',
            name='konum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ArslanTakipApp.location'),
        ),
    ]
