# Generated by Django 4.2.2 on 2024-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0102_hammaddebillettakip_konum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hammaddebillettakip',
            name='irsaliye_no',
        ),
        migrations.AddField(
            model_name='hammaddebillettakip',
            name='gelen_kimlik',
            field=models.IntegerField(null=True),
        ),
    ]
