# Generated by Django 4.2.2 on 2024-10-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0103_remove_hammaddebillettakip_irsaliye_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HammaddeBillet',
            fields=[
                ('billet_no', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('guncel_boy', models.FloatField(blank=True, null=True)),
                ('sira', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HammaddeBilletStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parti_no', models.CharField(blank=True, null=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now=True)),
                ('boy', models.FloatField(blank=True, null=True)),
                ('adet', models.IntegerField(blank=True, null=True)),
                ('kg', models.FloatField(blank=True, null=True)),
                ('stok_cinsi', models.CharField(blank=True, null=True)),
                ('transfer_giren_kg', models.FloatField(blank=True, null=True)),
                ('aciklama', models.CharField(blank=True, null=True)),
                ('gelen_kimlik', models.IntegerField(null=True)),
                ('konum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ArslanTakipApp.location')),
            ],
        ),
        migrations.DeleteModel(
            name='HammaddeBilletTakip',
        ),
        migrations.AddField(
            model_name='hammaddebillet',
            name='stok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArslanTakipApp.hammaddebilletstok'),
        ),
    ]
