# Generated by Django 4.2.2 on 2024-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0105_remove_hammaddebilletstok_transfer_giren_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammaddebillet',
            name='tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
