# Generated by Django 4.2.2 on 2024-10-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0106_hammaddebillet_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='HammaddeBilletCubuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billet_no', models.CharField(blank=True, null=True)),
                ('guncel_boy', models.FloatField(blank=True, null=True)),
                ('sira', models.IntegerField(blank=True, null=True)),
                ('tarih', models.DateTimeField(blank=True, null=True)),
                ('stok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArslanTakipApp.hammaddebilletstok')),
            ],
        ),
        migrations.DeleteModel(
            name='HammaddeBillet',
        ),
    ]
