# Generated by Django 4.2.2 on 2024-10-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0107_hammaddebilletcubuk_delete_hammaddebillet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hammaddebilletcubuk',
            name='stok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ArslanTakipApp.hammaddebilletstok'),
        ),
    ]
