# Generated by Django 4.2.2 on 2024-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0108_alter_hammaddebilletcubuk_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammaddebilletcubuk',
            name='parti_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
