# Generated by Django 4.2.2 on 2024-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0109_hammaddebilletcubuk_parti_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(null=True)),
                ('locationName', models.CharField(null=True)),
                ('kalip_list', models.TextField(null=True)),
            ],
            options={
                'db_table': 'View_DiesInLocations',
                'managed': False,
            },
        ),
    ]
