# Generated by Django 4.2.2 on 2024-11-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0111_rename_finish_reason_presuretimtakip_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hammaddebilletcubuk',
            name='pres_uretim_takip',
        ),
        migrations.RemoveField(
            model_name='presuretimtakip',
            name='bitis_datetime',
        ),
        migrations.RemoveField(
            model_name='presuretimtakip',
            name='event',
        ),
        migrations.RemoveField(
            model_name='presuretimtakip',
            name='reason',
        ),
    ]
