# Generated by Django 4.2.2 on 2025-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0113_io_list_recipe_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepet_no', models.CharField(blank=True, null=True)),
                ('baslangic_saati', models.DateTimeField(blank=True, null=True)),
                ('bitis_saati', models.DateTimeField(blank=True, null=True)),
                ('pres_kodu', models.CharField(blank=True, null=True)),
                ('yuklenen', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
