# Generated by Django 4.2.2 on 2025-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0114_sepet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlcData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc', models.CharField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('stop', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(blank=True, null=True)),
                ('singular_params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plcdata',
                'managed': False,
            },
        ),
    ]
