# Generated by Django 4.2.2 on 2025-01-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0115_plcdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sepet',
            options={'permissions': [('view_4500_uretim', 'Uretim Gorme Yetkisi Var')]},
        ),
    ]
