# Generated by Django 4.2.2 on 2025-02-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0116_alter_sepet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KartDagilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_no', models.CharField(blank=True, null=True)),
                ('profil_gr', models.FloatField(blank=True, null=True)),
                ('secilen_ext', models.JSONField(blank=True, null=True)),
                ('secilen_sepet', models.JSONField(blank=True, null=True)),
                ('secilen_siparis', models.JSONField(blank=True, null=True)),
                ('dagitilan_kartlar', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
