# Generated by Django 4.2.2 on 2025-02-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0117_kartdagilim'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartdagilim',
            name='tarih',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
