# Generated by Django 4.2.2 on 2025-02-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0119_kalipmuadil'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Kategori',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='yudaonaydurum',
            table='view1_yudadurum4',
        ),
    ]
