# Generated by Django 4.2.2 on 2025-03-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0122_eventdata_alter_unitofmeasure_conversion_factor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaldata',
            old_name='event_id',
            new_name='event',
        ),
    ]
