# Generated by Django 4.2.2 on 2025-03-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0124_remove_temporaldata_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kalip',
        ),
    ]
