# Generated by Django 4.2.2 on 2025-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0126_alter_parameter_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yudaform',
            name='YudaNo',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
