# Generated by Django 4.2.2 on 2025-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0127_alter_yudaform_yudano'),
    ]

    operations = [
        migrations.AddField(
            model_name='yudaform',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
