# Generated by Django 4.2.2 on 2025-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0128_yudaform_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilNo', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'View028_ProfilListe',
                'managed': False,
            },
        ),
    ]
