# Generated by Django 5.0 on 2025-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0129_profilms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
