# Generated by Django 5.0 on 2025-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0132_yuda_parent_alter_yuda_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaliphaneIsEmri',
            fields=[
                ('KartNo', models.CharField(blank=True, primary_key=True, serialize=False)),
                ('Kimlik', models.IntegerField(blank=True, null=True)),
                ('UrtKimlik', models.IntegerField(blank=True, null=True)),
                ('Tree_StokKodu', models.CharField(blank=True, null=True)),
                ('StokKodu', models.CharField(blank=True, null=True)),
                ('OperasyonGrupKodu', models.CharField(blank=True, null=True)),
                ('OperasyonKodu', models.CharField(blank=True, null=True)),
                ('OperasyonAdi', models.CharField(blank=True, null=True)),
                ('Durum', models.CharField(blank=True, null=True)),
                ('Bolum', models.CharField(blank=True, null=True)),
                ('UrtSiparisNo', models.CharField(blank=True, null=True)),
                ('Operasyon', models.CharField(blank=True, null=True)),
                ('SiparisNo', models.CharField(blank=True, null=True)),
                ('Aciklama', models.CharField(blank=True, null=True)),
                ('Varyant1', models.CharField(blank=True, null=True)),
                ('Varyant2', models.CharField(blank=True, null=True)),
                ('Varyant3', models.CharField(blank=True, null=True)),
                ('Varyant4', models.CharField(blank=True, null=True)),
                ('Varyant5', models.CharField(blank=True, null=True)),
                ('Varyant6', models.CharField(blank=True, null=True)),
                ('Varyant7', models.CharField(blank=True, null=True)),
                ('Varyant8', models.CharField(blank=True, null=True)),
                ('Varyant9', models.CharField(blank=True, null=True)),
                ('Varyant10', models.CharField(blank=True, null=True)),
                ('Varyant11', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'View_URT_IsEmri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MusteriFirma',
            fields=[
                ('FirmaKodu', models.CharField(blank=True, primary_key=True, serialize=False)),
                ('FirmaAdi', models.CharField(blank=True, null=True)),
                ('MusteriTemsilcisi', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'View009_FirmaListesi',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='IsPinned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
