# Generated by Django 5.0 on 2025-10-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0133_kaliphaneisemri_musterifirma_comment_ispinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='OriginId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
