# Generated by Django 5.0 on 2025-10-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0134_comment_originid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
