# Generated by Django 5.0 on 2025-10-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0135_uploadfile_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieInfo',
            fields=[
                ('die_no', models.CharField(blank=True, primary_key=True, serialize=False)),
                ('profil_no', models.CharField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
