# Generated by Django 5.0 on 2025-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0136_dieinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieinfo',
            name='die_no',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dieinfo',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dieinfo',
            name='profil_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
