# Generated by Django 5.0 on 2025-11-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0137_alter_dieinfo_die_no_alter_dieinfo_meta_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dieinfo',
            options={'permissions': [('edit_dieinfo', 'DieInfo Düzenleme Yetkisi')]},
        ),
    ]
