# Generated by Django 5.0 on 2026-06-04 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0138_alter_dieinfo_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.CharField(blank=True, choices=[('everyone', 'Herkes'), ('only_me', 'Sadece Ben'), ('specific_users', 'Belirli Kullanıcılar'), ('specific_groups', 'Belirli Gruplar')], default='everyone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='visibility_groups',
            field=models.ManyToManyField(blank=True, help_text="'specific_groups' görünürlüğünde bu yorumu görebilecek gruplar", related_name='permitted_comments', to='auth.group'),
        ),
        migrations.AddField(
            model_name='comment',
            name='visibility_users',
            field=models.ManyToManyField(blank=True, help_text="'specific_users' görünürlüğünde bu yorumu görebilecek kullanıcılar", related_name='permitted_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
