# Generated by Django 5.0 on 2026-08-14 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0139_comment_visibility_comment_visibility_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('IN_TRANSIT', 'Yolda'), ('COMPLETED', 'Tamamlandı')], default='IN_TRANSIT', max_length=20, verbose_name='Durum')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('baslatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baslattigi_transferler', to=settings.AUTH_USER_MODEL, verbose_name='Başlatan')),
                ('hedef_lokasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_hedef', to='ArslanTakipApp.location', verbose_name='Hedef Lokasyon')),
                ('kaynak_lokasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_kaynak', to='ArslanTakipApp.location', verbose_name='Kaynak Lokasyon')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transferler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='TransferMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj_metni', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('sistem_mesaji', models.BooleanField(default=False, verbose_name='Sistem Mesajı mı?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('yazar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='ArslanTakipApp.transittransfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Mesajı',
                'verbose_name_plural': 'Transfer Mesajları',
                'ordering': ['olusturma_tarihi'],
            },
        ),
    ]
