# Generated by Django 5.0 on 2026-08-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0140_transittransfer_transfermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='module_tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modül Etiketi'),
        ),
    ]
