# Generated by Django 5.0 on 2026-08-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArslanTakipApp', '0141_location_module_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transittransfer',
            name='islem_sonucu',
            field=models.CharField(blank=True, choices=[('KABUL', 'Kabul'), ('SARTLI_KABUL', 'Şartlı Kabul'), ('RET', 'Ret')], max_length=20, null=True, verbose_name='İşlem Sonucu'),
        ),
        migrations.AlterField(
            model_name='transittransfer',
            name='durum',
            field=models.CharField(choices=[('IN_TRANSIT', 'Yolda'), ('REJECTED', 'Reddedildi / İade'), ('COMPLETED', 'Tamamlandı')], default='IN_TRANSIT', max_length=20, verbose_name='Durum'),
        ),
    ]
