# Generated by Django 4.2.2 on 2023-07-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=255, verbose_name='Grup İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=255, verbose_name='Depo İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=255, verbose_name='Stok Türü')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=255, verbose_name='Birim')),
            ],
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockNo', models.CharField(max_length=255, unique=True, verbose_name='Stok Kodu')),
                ('StockName', models.CharField(max_length=255, verbose_name='Stok İsmi')),
                ('StockDetail', models.CharField(max_length=255, verbose_name='Stok Detayı')),
                ('PackageAmount', models.DecimalField(decimal_places=3, max_digits=255, null=True, verbose_name='Paket İçi Miktar')),
                ('Equivalent', models.CharField(max_length=255, verbose_name='Muadil Stok')),
                ('Brand', models.CharField(max_length=255, verbose_name='Marka')),
                ('ProductName', models.CharField(max_length=255, verbose_name='Ürün İsmi')),
                ('CriticStock', models.DecimalField(decimal_places=3, max_digits=255, null=True, verbose_name='Kritik Stok Miktarı')),
                ('MinOrderAmount', models.DecimalField(decimal_places=3, max_digits=255, null=True, verbose_name='Minimum Sipariş Miktarı')),
                ('PackageUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_uit', to='StokApp.unit', verbose_name='Ambalaj Birimi')),
                ('StockGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StokApp.group')),
                ('StockStore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StokApp.store', verbose_name='Depo')),
                ('StockType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StokApp.type', verbose_name='Stok Türü')),
                ('StockUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_unit', to='StokApp.unit', verbose_name='Kullanılan Ölçü Birimi')),
            ],
        ),
    ]
